package database

import (
	"chinese-learning-app/internal/models"
	"chinese-learning-app/internal/repositories"
	"time"
)

type toneBattleSeedEntry struct {
	Hanzi    string
	Syllable string
	Pinyin   string
	Tone     int
}

func SeedToneBattleQuestions(repo *repositories.ToneBattleRepository) error {
	count, err := repo.CountQuestions()
	if err != nil {
		return err
	}
	if count >= 200 {
		return nil
	}

	now := time.Now()
	entries := []toneBattleSeedEntry{
		{Hanzi: "妈", Syllable: "ma1", Pinyin: "mā", Tone: 1},
		{Hanzi: "八", Syllable: "ba1", Pinyin: "bā", Tone: 1},
		{Hanzi: "搭", Syllable: "da1", Pinyin: "dā", Tone: 1},
		{Hanzi: "他", Syllable: "ta1", Pinyin: "tā", Tone: 1},
		{Hanzi: "拉", Syllable: "la1", Pinyin: "lā", Tone: 1},
		{Hanzi: "发", Syllable: "fa1", Pinyin: "fā", Tone: 1},
		{Hanzi: "花", Syllable: "hua1", Pinyin: "huā", Tone: 1},
		{Hanzi: "家", Syllable: "jia1", Pinyin: "jiā", Tone: 1},
		{Hanzi: "瓜", Syllable: "gua1", Pinyin: "guā", Tone: 1},
		{Hanzi: "开", Syllable: "kai1", Pinyin: "kāi", Tone: 1},
		{Hanzi: "杯", Syllable: "bei1", Pinyin: "bēi", Tone: 1},
		{Hanzi: "飞", Syllable: "fei1", Pinyin: "fēi", Tone: 1},
		{Hanzi: "哥", Syllable: "ge1", Pinyin: "gē", Tone: 1},
		{Hanzi: "车", Syllable: "che1", Pinyin: "chē", Tone: 1},
		{Hanzi: "书", Syllable: "shu1", Pinyin: "shū", Tone: 1},
		{Hanzi: "衣", Syllable: "yi1", Pinyin: "yī", Tone: 1},
		{Hanzi: "春", Syllable: "chun1", Pinyin: "chūn", Tone: 1},
		{Hanzi: "天", Syllable: "tian1", Pinyin: "tiān", Tone: 1},
		{Hanzi: "星", Syllable: "xing1", Pinyin: "xīng", Tone: 1},
		{Hanzi: "东", Syllable: "dong1", Pinyin: "dōng", Tone: 1},
		{Hanzi: "风", Syllable: "feng1", Pinyin: "fēng", Tone: 1},
		{Hanzi: "山", Syllable: "shan1", Pinyin: "shān", Tone: 1},
		{Hanzi: "猫", Syllable: "mao1", Pinyin: "māo", Tone: 1},
		{Hanzi: "高", Syllable: "gao1", Pinyin: "gāo", Tone: 1},
		{Hanzi: "灯", Syllable: "deng1", Pinyin: "dēng", Tone: 1},
		{Hanzi: "钟", Syllable: "zhong1", Pinyin: "zhōng", Tone: 1},
		{Hanzi: "安", Syllable: "an1", Pinyin: "ān", Tone: 1},
		{Hanzi: "秋", Syllable: "qiu1", Pinyin: "qiū", Tone: 1},
		{Hanzi: "边", Syllable: "bian1", Pinyin: "biān", Tone: 1},
		{Hanzi: "军", Syllable: "jun1", Pinyin: "jūn", Tone: 1},
		{Hanzi: "灰", Syllable: "hui1", Pinyin: "huī", Tone: 1},
		{Hanzi: "沙", Syllable: "sha1", Pinyin: "shā", Tone: 1},
		{Hanzi: "租", Syllable: "zu1", Pinyin: "zū", Tone: 1},
		{Hanzi: "粗", Syllable: "cu1", Pinyin: "cū", Tone: 1},
		{Hanzi: "森", Syllable: "sen1", Pinyin: "sēn", Tone: 1},
		{Hanzi: "邦", Syllable: "bang1", Pinyin: "bāng", Tone: 1},
		{Hanzi: "空", Syllable: "kong1", Pinyin: "kōng", Tone: 1},
		{Hanzi: "抛", Syllable: "pao1", Pinyin: "pāo", Tone: 1},
		{Hanzi: "胎", Syllable: "tai1", Pinyin: "tāi", Tone: 1},
		{Hanzi: "妞", Syllable: "niu1", Pinyin: "niū", Tone: 1},

		{Hanzi: "麻", Syllable: "ma2", Pinyin: "má", Tone: 2},
		{Hanzi: "拔", Syllable: "ba2", Pinyin: "bá", Tone: 2},
		{Hanzi: "答", Syllable: "da2", Pinyin: "dá", Tone: 2},
		{Hanzi: "爬", Syllable: "pa2", Pinyin: "pá", Tone: 2},
		{Hanzi: "拿", Syllable: "na2", Pinyin: "ná", Tone: 2},
		{Hanzi: "牙", Syllable: "ya2", Pinyin: "yá", Tone: 2},
		{Hanzi: "茶", Syllable: "cha2", Pinyin: "chá", Tone: 2},
		{Hanzi: "蛇", Syllable: "she2", Pinyin: "shé", Tone: 2},
		{Hanzi: "河", Syllable: "he2", Pinyin: "hé", Tone: 2},
		{Hanzi: "鹅", Syllable: "e2", Pinyin: "é", Tone: 2},
		{Hanzi: "伯", Syllable: "bo2", Pinyin: "bó", Tone: 2},
		{Hanzi: "婆", Syllable: "po2", Pinyin: "pó", Tone: 2},
		{Hanzi: "驼", Syllable: "tuo2", Pinyin: "tuó", Tone: 2},
		{Hanzi: "罗", Syllable: "luo2", Pinyin: "luó", Tone: 2},
		{Hanzi: "白", Syllable: "bai2", Pinyin: "bái", Tone: 2},
		{Hanzi: "梅", Syllable: "mei2", Pinyin: "méi", Tone: 2},
		{Hanzi: "谁", Syllable: "shei2", Pinyin: "shéi", Tone: 2},
		{Hanzi: "楼", Syllable: "lou2", Pinyin: "lóu", Tone: 2},
		{Hanzi: "牛", Syllable: "niu2", Pinyin: "niú", Tone: 2},
		{Hanzi: "学", Syllable: "xue2", Pinyin: "xué", Tone: 2},
		{Hanzi: "节", Syllable: "jie2", Pinyin: "jié", Tone: 2},
		{Hanzi: "茄", Syllable: "qie2", Pinyin: "qié", Tone: 2},
		{Hanzi: "桥", Syllable: "qiao2", Pinyin: "qiáo", Tone: 2},
		{Hanzi: "鱼", Syllable: "yu2", Pinyin: "yú", Tone: 2},
		{Hanzi: "云", Syllable: "yun2", Pinyin: "yún", Tone: 2},
		{Hanzi: "熊", Syllable: "xiong2", Pinyin: "xióng", Tone: 2},
		{Hanzi: "红", Syllable: "hong2", Pinyin: "hóng", Tone: 2},
		{Hanzi: "虫", Syllable: "chong2", Pinyin: "chóng", Tone: 2},
		{Hanzi: "竹", Syllable: "zhu2", Pinyin: "zhú", Tone: 2},
		{Hanzi: "词", Syllable: "ci2", Pinyin: "cí", Tone: 2},
		{Hanzi: "才", Syllable: "cai2", Pinyin: "cái", Tone: 2},
		{Hanzi: "房", Syllable: "fang2", Pinyin: "fáng", Tone: 2},
		{Hanzi: "黄", Syllable: "huang2", Pinyin: "huáng", Tone: 2},
		{Hanzi: "阳", Syllable: "yang2", Pinyin: "yáng", Tone: 2},
		{Hanzi: "人", Syllable: "ren2", Pinyin: "rén", Tone: 2},
		{Hanzi: "明", Syllable: "ming2", Pinyin: "míng", Tone: 2},
		{Hanzi: "龙", Syllable: "long2", Pinyin: "lóng", Tone: 2},
		{Hanzi: "田", Syllable: "tian2", Pinyin: "tián", Tone: 2},
		{Hanzi: "兰", Syllable: "lan2", Pinyin: "lán", Tone: 2},
		{Hanzi: "南", Syllable: "nan2", Pinyin: "nán", Tone: 2},

		{Hanzi: "马", Syllable: "ma3", Pinyin: "mǎ", Tone: 3},
		{Hanzi: "把", Syllable: "ba3", Pinyin: "bǎ", Tone: 3},
		{Hanzi: "打", Syllable: "da3", Pinyin: "dǎ", Tone: 3},
		{Hanzi: "塔", Syllable: "ta3", Pinyin: "tǎ", Tone: 3},
		{Hanzi: "哪", Syllable: "na3", Pinyin: "nǎ", Tone: 3},
		{Hanzi: "卡", Syllable: "ka3", Pinyin: "kǎ", Tone: 3},
		{Hanzi: "法", Syllable: "fa3", Pinyin: "fǎ", Tone: 3},
		{Hanzi: "雅", Syllable: "ya3", Pinyin: "yǎ", Tone: 3},
		{Hanzi: "瓦", Syllable: "wa3", Pinyin: "wǎ", Tone: 3},
		{Hanzi: "海", Syllable: "hai3", Pinyin: "hǎi", Tone: 3},
		{Hanzi: "北", Syllable: "bei3", Pinyin: "běi", Tone: 3},
		{Hanzi: "美", Syllable: "mei3", Pinyin: "měi", Tone: 3},
		{Hanzi: "给", Syllable: "gei3", Pinyin: "gěi", Tone: 3},
		{Hanzi: "水", Syllable: "shui3", Pinyin: "shuǐ", Tone: 3},
		{Hanzi: "雨", Syllable: "yu3", Pinyin: "yǔ", Tone: 3},
		{Hanzi: "我", Syllable: "wo3", Pinyin: "wǒ", Tone: 3},
		{Hanzi: "火", Syllable: "huo3", Pinyin: "huǒ", Tone: 3},
		{Hanzi: "果", Syllable: "guo3", Pinyin: "guǒ", Tone: 3},
		{Hanzi: "好", Syllable: "hao3", Pinyin: "hǎo", Tone: 3},
		{Hanzi: "草", Syllable: "cao3", Pinyin: "cǎo", Tone: 3},
		{Hanzi: "早", Syllable: "zao3", Pinyin: "zǎo", Tone: 3},
		{Hanzi: "走", Syllable: "zou3", Pinyin: "zǒu", Tone: 3},
		{Hanzi: "狗", Syllable: "gou3", Pinyin: "gǒu", Tone: 3},
		{Hanzi: "手", Syllable: "shou3", Pinyin: "shǒu", Tone: 3},
		{Hanzi: "酒", Syllable: "jiu3", Pinyin: "jiǔ", Tone: 3},
		{Hanzi: "雪", Syllable: "xue3", Pinyin: "xuě", Tone: 3},
		{Hanzi: "姐", Syllable: "jie3", Pinyin: "jiě", Tone: 3},
		{Hanzi: "请", Syllable: "qing3", Pinyin: "qǐng", Tone: 3},
		{Hanzi: "影", Syllable: "ying3", Pinyin: "yǐng", Tone: 3},
		{Hanzi: "领", Syllable: "ling3", Pinyin: "lǐng", Tone: 3},
		{Hanzi: "饼", Syllable: "bing3", Pinyin: "bǐng", Tone: 3},
		{Hanzi: "想", Syllable: "xiang3", Pinyin: "xiǎng", Tone: 3},
		{Hanzi: "两", Syllable: "liang3", Pinyin: "liǎng", Tone: 3},
		{Hanzi: "跑", Syllable: "pao3", Pinyin: "pǎo", Tone: 3},
		{Hanzi: "老", Syllable: "lao3", Pinyin: "lǎo", Tone: 3},
		{Hanzi: "友", Syllable: "you3", Pinyin: "yǒu", Tone: 3},
		{Hanzi: "暖", Syllable: "nuan3", Pinyin: "nuǎn", Tone: 3},
		{Hanzi: "选", Syllable: "xuan3", Pinyin: "xuǎn", Tone: 3},
		{Hanzi: "碗", Syllable: "wan3", Pinyin: "wǎn", Tone: 3},
		{Hanzi: "远", Syllable: "yuan3", Pinyin: "yuǎn", Tone: 3},

		{Hanzi: "骂", Syllable: "ma4", Pinyin: "mà", Tone: 4},
		{Hanzi: "爸", Syllable: "ba4", Pinyin: "bà", Tone: 4},
		{Hanzi: "大", Syllable: "da4", Pinyin: "dà", Tone: 4},
		{Hanzi: "怕", Syllable: "pa4", Pinyin: "pà", Tone: 4},
		{Hanzi: "踏", Syllable: "ta4", Pinyin: "tà", Tone: 4},
		{Hanzi: "辣", Syllable: "la4", Pinyin: "là", Tone: 4},
		{Hanzi: "画", Syllable: "hua4", Pinyin: "huà", Tone: 4},
		{Hanzi: "下", Syllable: "xia4", Pinyin: "xià", Tone: 4},
		{Hanzi: "架", Syllable: "jia4", Pinyin: "jià", Tone: 4},
		{Hanzi: "挂", Syllable: "gua4", Pinyin: "guà", Tone: 4},
		{Hanzi: "怪", Syllable: "guai4", Pinyin: "guài", Tone: 4},
		{Hanzi: "会", Syllable: "hui4", Pinyin: "huì", Tone: 4},
		{Hanzi: "对", Syllable: "dui4", Pinyin: "duì", Tone: 4},
		{Hanzi: "最", Syllable: "zui4", Pinyin: "zuì", Tone: 4},
		{Hanzi: "泪", Syllable: "lei4", Pinyin: "lèi", Tone: 4},
		{Hanzi: "谢", Syllable: "xie4", Pinyin: "xiè", Tone: 4},
		{Hanzi: "月", Syllable: "yue4", Pinyin: "yuè", Tone: 4},
		{Hanzi: "去", Syllable: "qu4", Pinyin: "qù", Tone: 4},
		{Hanzi: "绿", Syllable: "lv4", Pinyin: "lǜ", Tone: 4},
		{Hanzi: "兔", Syllable: "tu4", Pinyin: "tù", Tone: 4},
		{Hanzi: "树", Syllable: "shu4", Pinyin: "shù", Tone: 4},
		{Hanzi: "日", Syllable: "ri4", Pinyin: "rì", Tone: 4},
		{Hanzi: "课", Syllable: "ke4", Pinyin: "kè", Tone: 4},
		{Hanzi: "热", Syllable: "re4", Pinyin: "rè", Tone: 4},
		{Hanzi: "做", Syllable: "zuo4", Pinyin: "zuò", Tone: 4},
		{Hanzi: "错", Syllable: "cuo4", Pinyin: "cuò", Tone: 4},
		{Hanzi: "四", Syllable: "si4", Pinyin: "sì", Tone: 4},
		{Hanzi: "色", Syllable: "se4", Pinyin: "sè", Tone: 4},
		{Hanzi: "送", Syllable: "song4", Pinyin: "sòng", Tone: 4},
		{Hanzi: "动", Syllable: "dong4", Pinyin: "dòng", Tone: 4},
		{Hanzi: "用", Syllable: "yong4", Pinyin: "yòng", Tone: 4},
		{Hanzi: "看", Syllable: "kan4", Pinyin: "kàn", Tone: 4},
		{Hanzi: "胖", Syllable: "pang4", Pinyin: "pàng", Tone: 4},
		{Hanzi: "亮", Syllable: "liang4", Pinyin: "liàng", Tone: 4},
		{Hanzi: "放", Syllable: "fang4", Pinyin: "fàng", Tone: 4},
		{Hanzi: "唱", Syllable: "chang4", Pinyin: "chàng", Tone: 4},
		{Hanzi: "到", Syllable: "dao4", Pinyin: "dào", Tone: 4},
		{Hanzi: "告", Syllable: "gao4", Pinyin: "gào", Tone: 4},
		{Hanzi: "路", Syllable: "lu4", Pinyin: "lù", Tone: 4},
		{Hanzi: "够", Syllable: "gou4", Pinyin: "gòu", Tone: 4},

		{Hanzi: "吗", Syllable: "ma5", Pinyin: "ma", Tone: 5},
		{Hanzi: "吧", Syllable: "ba5", Pinyin: "ba", Tone: 5},
		{Hanzi: "呢", Syllable: "ne5", Pinyin: "ne", Tone: 5},
		{Hanzi: "了", Syllable: "le5", Pinyin: "le", Tone: 5},
		{Hanzi: "的", Syllable: "de5", Pinyin: "de", Tone: 5},
		{Hanzi: "着", Syllable: "zhe5", Pinyin: "zhe", Tone: 5},
		{Hanzi: "子", Syllable: "zi5", Pinyin: "zi", Tone: 5},
		{Hanzi: "们", Syllable: "men5", Pinyin: "men", Tone: 5},
		{Hanzi: "头", Syllable: "tou5", Pinyin: "tou", Tone: 5},
		{Hanzi: "么", Syllable: "me5", Pinyin: "me", Tone: 5},
		{Hanzi: "啊", Syllable: "a5", Pinyin: "a", Tone: 5},
		{Hanzi: "呀", Syllable: "ya5", Pinyin: "ya", Tone: 5},
		{Hanzi: "哇", Syllable: "wa5", Pinyin: "wa", Tone: 5},
		{Hanzi: "嘛", Syllable: "ma5_alt1", Pinyin: "ma", Tone: 5},
		{Hanzi: "啦", Syllable: "la5", Pinyin: "la", Tone: 5},
		{Hanzi: "咯", Syllable: "lo5", Pinyin: "lo", Tone: 5},
		{Hanzi: "喽", Syllable: "lou5", Pinyin: "lou", Tone: 5},
		{Hanzi: "嘞", Syllable: "lei5", Pinyin: "lei", Tone: 5},
		{Hanzi: "咧", Syllable: "lie5", Pinyin: "lie", Tone: 5},
		{Hanzi: "呦", Syllable: "you5", Pinyin: "you", Tone: 5},
		{Hanzi: "哪", Syllable: "na5", Pinyin: "na", Tone: 5},
		{Hanzi: "得", Syllable: "dei5", Pinyin: "dei", Tone: 5},
		{Hanzi: "个", Syllable: "ge5", Pinyin: "ge", Tone: 5},
		{Hanzi: "过", Syllable: "guo5", Pinyin: "guo", Tone: 5},
		{Hanzi: "来", Syllable: "lai5", Pinyin: "lai", Tone: 5},
		{Hanzi: "去", Syllable: "qu5", Pinyin: "qu", Tone: 5},
		{Hanzi: "喏", Syllable: "nuo5", Pinyin: "nuo", Tone: 5},
		{Hanzi: "罗", Syllable: "luo5", Pinyin: "luo", Tone: 5},
		{Hanzi: "喔", Syllable: "wo5", Pinyin: "wo", Tone: 5},
		{Hanzi: "欸", Syllable: "ei5", Pinyin: "ei", Tone: 5},
		{Hanzi: "嗨", Syllable: "hai5", Pinyin: "hai", Tone: 5},
		{Hanzi: "哟", Syllable: "yo5", Pinyin: "yo", Tone: 5},
		{Hanzi: "啰", Syllable: "luo5_alt1", Pinyin: "luo", Tone: 5},
		{Hanzi: "呀", Syllable: "ya5_alt1", Pinyin: "ya", Tone: 5},
		{Hanzi: "罢", Syllable: "ba5_alt1", Pinyin: "ba", Tone: 5},
		{Hanzi: "嘛", Syllable: "ma5_alt2", Pinyin: "ma", Tone: 5},
		{Hanzi: "哈", Syllable: "ha5", Pinyin: "ha", Tone: 5},
		{Hanzi: "嘿", Syllable: "hei5", Pinyin: "hei", Tone: 5},
		{Hanzi: "哦", Syllable: "o5", Pinyin: "o", Tone: 5},
		{Hanzi: "呵", Syllable: "he5", Pinyin: "he", Tone: 5},
	}

	questions := make([]models.ToneBattleQuestion, 0, len(entries))
	for _, entry := range entries {
		questions = append(questions, models.ToneBattleQuestion{
			Hanzi:     entry.Hanzi,
			Syllable:  entry.Syllable,
			Pinyin:    entry.Pinyin,
			Tone:      entry.Tone,
			AudioPath: "tts://" + entry.Hanzi,
			Category:  "foundation",
			CreatedAt: now,
			UpdatedAt: now,
		})
	}

	return repo.CreateQuestions(questions)
}
